import { z } from 'zod';

export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  RATE_LIMITED = 'RATE_LIMITED',
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_COOLDOWN = 'OTP_COOLDOWN',
  OTP_MAX_ATTEMPTS = 'OTP_MAX_ATTEMPTS',
  CONFLICT = 'CONFLICT',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Domain-Specific Errors
  ORDER_NOT_PUBLISHABLE = 'ORDER_NOT_PUBLISHABLE',
  ILLEGAL_TRANSITION = 'ILLEGAL_TRANSITION',
  SUBSCRIPTION_REQUIRED = 'SUBSCRIPTION_REQUIRED',
  VERIFICATION_LEVEL_TOO_LOW = 'VERIFICATION_LEVEL_TOO_LOW',
  MAX_STOPS_EXCEEDED = 'MAX_STOPS_EXCEEDED',
  INVALID_WAIT_MODE = 'INVALID_WAIT_MODE',
  OWNERSHIP_VIOLATION = 'OWNERSHIP_VIOLATION',
  ORDER_ALREADY_AGREED = 'ORDER_ALREADY_AGREED',
  AGREEMENT_IMMUTABLE = 'AGREEMENT_IMMUTABLE',
  OFFER_EXPIRED = 'OFFER_EXPIRED',
  OFFER_ROUND_LIMIT_REACHED = 'OFFER_ROUND_LIMIT_REACHED',
}

export const ApiErrorEnvelopeSchema = z.object({
  statusCode: z.number(),
  errorCode: z.nativeEnum(ErrorCode),
  message: z.string(),
  i18nKey: z.string().optional(),
  details: z.any().optional(),
  timestamp: z.string(),
  path: z.string(),
  requestId: z.string().optional(),
});

export type ApiErrorEnvelope = z.infer<typeof ApiErrorEnvelopeSchema>;
